language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zev
  password:
    secure: wnP/0lBjIAssfaU2ttoKMISkLvxvLbchY2vvyL0QGeXfuF+0xbTJvv6sVvdGtFgGPXdlPKfVJ8buUtrYTK8tjxbsj+s3M4cWztoSA+4aqJKd+3ytM5xXcmJokACsGPdkZc6b7tI0SoK/IHyJ/hyfI06GXhaEH+wsSUtiyBr+2xaqxGmqQsTmOubvsl+tomqkyFUkkPzeYhPzWzc/WgbqSPiooY0kFwM+VxjPmilcUdEV78MLWQiTrwM+C7e/OgSEplJ/f8GK4YWGSm7UYxk7P3HUpfIYMsyXkGHuNEnqWWNdvGRS+clLtXZsaS6UFBud7Y0dfuMdxrqgBQETMk9Kmv6blh16E0XP8VRvBhlIFBBR1h9IA9zcLDE2Yj57v/e3Q9Whq/EvzJWz3KZueANq3FGK73TnTCS6qGI5MbYFp3V7kPn1zBVvXA7kfN570mz8KO1cbse4nDsLpg4w7js+I8sz9OK/eHTHANT9qICqyCsLkarL/0572zLwZfOXBgDpfZOefKZ0UAeqErELvVG+uajzITaH06NmiRiPlSo473gyfGWBoBDbBV5vvhhajram1g62Xd8JYSG/pJ04NMDjp2+EMAphgYaX6Z5M+E0iiwakkShpoWNZqdxjEUBlnQ4F2xsKRWznAXlnYHF+AP3jplr91HRmeZmpT9Nv305cTDg=
  on:
    tags: true
    repo: zevav/zev
    python: 3.6
